# Generated by Django 4.1 on 2022-10-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('rate', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.CharField(max_length=140)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postDate', to='lifelog.sleeplog')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postUserId', to='lifelog.sleeplog')),
            ],
        ),
    ]
