# Generated by Django 4.1 on 2022-10-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0002_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='condition',
        ),
    ]
