# Generated by Django 4.1 on 2022-10-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0004_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='userId',
        ),
        migrations.AddField(
            model_name='condition',
            name='sleepLogId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lifelog.sleeplog'),
            preserve_default=False,
        ),
    ]
