# Generated by Django 4.1 on 2022-10-17 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0005_remove_condition_date_remove_condition_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
