# Generated by Django 4.1 on 2022-10-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0006_alter_condition_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
